import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — TalktheTalk",
};

const UPDATED = "19 June 2026";

function H({ children }: { children: React.ReactNode }) {
  return <h2 className="font-display text-2xl leading-tight mt-10 mb-3">{children}</h2>;
}
function P({ children }: { children: React.ReactNode }) {
  return <p className="text-sm leading-relaxed text-muted-foreground mb-3">{children}</p>;
}

export default function PrivacyPage() {
  return (
    <main className="grain min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-2xl px-5 py-10 sm:px-8">
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">← Back</Link>

        <h1 className="font-display text-4xl leading-tight mt-6 mb-1">Privacy Policy</h1>
        <p className="text-xs text-muted-foreground mb-2">Last updated: {UPDATED}</p>
        <P>
          This Privacy Policy explains how we collect and process your personal data when you use
          TalktheTalk (the &ldquo;Service&rdquo;), in accordance with the EU General Data Protection
          Regulation (GDPR) and Spanish data protection law.
        </P>

        <H>1. Who we are (Data Controller)</H>
        <P>
          The controller of your personal data is <strong>Sundae Education Technologies SL</strong>,
          Carrer de Joan Oliver, 22D, 2-1, Sant Cugat del Vallès, 08172, Spain.
          For any privacy questions or to exercise your rights, contact us at{" "}
          <a href="mailto:support@getsundae.ai" className="underline">support@getsundae.ai</a>.
        </P>

        <H>2. Data we collect</H>
        <P>We collect and process the following categories of personal data:</P>
        <ul className="list-disc pl-5 text-sm leading-relaxed text-muted-foreground mb-3 flex flex-col gap-1">
          <li><strong>Account data:</strong> your name, email address, and profile photo, provided through Google sign-in.</li>
          <li><strong>Professional profile:</strong> your LinkedIn profile URL and details derived from it (job title, company, company size, responsibilities), your self-reported English level and native language.</li>
          <li><strong>Learning data:</strong> your selected scenarios, practice sentences, conversation transcripts, voice recordings used for pronunciation assessment, and the scores and feedback generated.</li>
          <li><strong>Technical data:</strong> a session cookie required to keep you signed in, and standard server logs (e.g. IP address, timestamps) generated by our hosting provider.</li>
        </ul>

        <H>3. How we use your data and legal bases</H>
        <ul className="list-disc pl-5 text-sm leading-relaxed text-muted-foreground mb-3 flex flex-col gap-1">
          <li><strong>To provide the Service</strong> — create your account, build your personalised course, run practice conversations and generate feedback. Legal basis: <em>performance of a contract</em> (Art. 6(1)(b) GDPR).</li>
          <li><strong>To send service emails</strong> — e.g. welcome and feedback notifications. Legal basis: <em>performance of a contract</em>.</li>
          <li><strong>To send occasional re-engagement emails</strong> if you sign up but don&rsquo;t start practising. Legal basis: <em>legitimate interests</em> (Art. 6(1)(f)); you can opt out at any time.</li>
          <li><strong>To secure, maintain and improve the Service.</strong> Legal basis: <em>legitimate interests</em>.</li>
          <li><strong>To comply with legal obligations.</strong> Legal basis: <em>legal obligation</em> (Art. 6(1)(c)).</li>
        </ul>

        <H>4. Service providers (processors) and recipients</H>
        <P>
          We share data only with service providers who process it on our behalf, under data
          processing agreements:
        </P>
        <ul className="list-disc pl-5 text-sm leading-relaxed text-muted-foreground mb-3 flex flex-col gap-1">
          <li><strong>Google</strong> — authentication (sign-in).</li>
          <li><strong>Supabase</strong> — database and file storage (hosted in the EU, Ireland).</li>
          <li><strong>Vercel</strong> — application hosting (United States).</li>
          <li><strong>Microsoft Azure (OpenAI &amp; Speech)</strong> — generating your course, scenarios, feedback, text-to-speech and pronunciation assessment (EU, West Europe region).</li>
          <li><strong>Vapi</strong> — running the live voice conversation (United States).</li>
          <li><strong>Exa</strong> — reading your public LinkedIn profile content (United States).</li>
          <li><strong>Resend</strong> — sending transactional emails (United States).</li>
        </ul>
        <P>We do not sell your personal data.</P>

        <H>5. International transfers</H>
        <P>
          Some of our providers are located outside the European Economic Area (notably in the United
          States). Where data is transferred outside the EEA, we rely on appropriate safeguards such
          as the European Commission&rsquo;s Standard Contractual Clauses and, where applicable, the
          EU–US Data Privacy Framework.
        </P>

        <H>6. Data retention</H>
        <P>
          We keep your personal data for as long as your account is active. If you ask us to delete
          your account, we will delete your personal data without undue delay, except where we must
          retain certain information to comply with legal obligations. Server logs are kept for a
          limited period by our hosting provider.
        </P>

        <H>7. Your rights</H>
        <P>Under the GDPR you have the right to:</P>
        <ul className="list-disc pl-5 text-sm leading-relaxed text-muted-foreground mb-3 flex flex-col gap-1">
          <li>access, rectify or erase your personal data;</li>
          <li>restrict or object to our processing;</li>
          <li>data portability;</li>
          <li>withdraw consent at any time (without affecting prior processing);</li>
          <li>lodge a complaint with a supervisory authority — in Spain, the Agencia Española de Protección de Datos (AEPD), <a href="https://www.aepd.es" className="underline">www.aepd.es</a>.</li>
        </ul>
        <P>
          To exercise any of these rights, email{" "}
          <a href="mailto:support@getsundae.ai" className="underline">support@getsundae.ai</a>.
        </P>

        <H>8. Cookies</H>
        <P>
          We use only a strictly necessary cookie to keep you signed in. We do not use advertising or
          analytics tracking cookies. If this changes, we will update this policy and request consent
          where required.
        </P>

        <H>9. Security</H>
        <P>
          We take reasonable technical and organisational measures to protect your data. However, no
          method of transmission or storage is completely secure.
        </P>

        <H>10. Children</H>
        <P>The Service is intended for users aged 18 and over. We do not knowingly collect data from minors.</P>

        <H>11. Changes to this policy</H>
        <P>
          We may update this Privacy Policy from time to time. We will post the updated version here
          and change the &ldquo;Last updated&rdquo; date above.
        </P>

        <H>12. Contact</H>
        <P>
          Sundae Education Technologies SL — Carrer de Joan Oliver, 22D, 2-1, Sant Cugat del Vallès,
          08172, Spain. Email: <a href="mailto:support@getsundae.ai" className="underline">support@getsundae.ai</a>.
        </P>

        <p className="mt-10 text-xs text-muted-foreground">
          <Link href="/terms" className="underline">Terms of Service</Link>
        </p>
      </div>
    </main>
  );
}
